### variables
//@baseUrl = https://koapractice.herokuapp.com/api
@baseUrl = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTYzNDAwMTI5OCwiZXhwIjoxNjM0MDA0ODk4fQ.E7UWKxHnH0-AXRbW4CAJI0CCMtyqaVqU26RINzF9p-Q

### Login
POST {{baseUrl}}/auth/signing  HTTP/1.1
Content-Type: application/json

{
    "email": "chris@gmail.com",
    "password": "123456"
}

### Sign UP
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json

{
   "email": "chris@gmail.com",
    "firstName": "chris",
    "lastName": "castillo",
    "password": "123456",
    "confirmPassword": "123456",
    "role":"ROLE_ADMIN"
}

### Add collaborator
POST {{baseUrl}}/colaborador/add HTTP/1.1
Content-Type: application/json
x-auth-token: {{token}}

{
    "nombre_colaborador": "Julieta Sanchez",
    "fecha_nacimiento": "12/12/1989",
    "rfc": "saju891212",
    "fecha_inicio":"11/10/2021",
    "estado_colaborador": "notActive",
    "area":"engineering"
}

### Search all collaborators
GET {{baseUrl}}/colaborador
Content-Type: application/json
x-auth-token: {{token}}

### Search id collaborador
GET {{baseUrl}}/colaborador/6164e899f0f007504595cba5
Content-Type: application/json
x-auth-token: {{token}}

### Update collaborator
PUT {{baseUrl}}/colaborador/update/6164ea56d1ea44fdbd5ce25e
Content-Type: application/json
x-auth-token: {{token}}

{
    "nombre_colaborador": "Julieta VIRIDIANA Sanchez",
    "fecha_nacimiento": "12/12/1990",
    "rfc": "SAJU901212",
    "fecha_inicio":"11/10/2021",
    "estado_colaborador": "notActive",
    "area":"engineering 2a"
}

### Delete collaborator
DELETE {{baseUrl}}/colaborador/delete/6164ea56d1ea44fdbd5ce25e
Content-Type: application/json
x-auth-token: {{token}}